### PR TITLE
Added method to set the partition

### PR DESCRIPTION
**Pull request by accelerated**

### CODE REVIEW

**Comment by mfontanini** [comment]
I'm not really a fan of having setters for everything. In which context do you not know the partition during construction? The (topic, partition) is basically an identifier for the object, that probably shouldn't be changing.

**Comment by accelerated** [comment]
In this scenario, we have a consumer cluster reading a topic, the configuration is the same across the cluster. However each instance gets a static partition assignment either in a separate file or from db. Therefore we create the global config first, then use setters for the respective partitions and offests. So it's nice to have, otherwise you need to delay the creation of these objects.
Secondly, you have a constructor that only takes a topic. How are you supposed to set the partition in that case?

**Comment by mfontanini** [comment]
Fair enough! I guess normally I'd just keep the topic name and build the `TopicPartition`s when needed but I understand if you may want to avoid the `string` memory allocations after whatever setup phase you have.

**Comment by accelerated** [comment]
Thanks!

**Pull request merged**
