### PR TITLE
Add support for Buffer construction via raw arrays

### PR DESCRIPTION
**Pull request by tgaldes**

### CODE REVIEW

**Comment by accelerated** [comment]
Not sure this should have been merged. It was already adressed by PR#147

**Comment by mfontanini** [comment]
Ugh true, how did this even compile?

**Comment by mfontanini** [comment]
So yeah no, this didn't compile https://travis-ci.org/mfontanini/cppkafka/jobs/468738999

**Comment by mfontanini** [comment]
For future reference @accelerated, please don't create a PR that duplicates a fix that another outstanding PR is already fixing. This is still on me for not double checking though.

Sorry @tgaldes that your commit had to be reverted!

**Comment by accelerated** [comment]
Sure, but i mentioned it in my PR tho. Also the other one had been outstanding for a month and i assumed @tgaldes had given up on it.

**Pull request merged**
