### PR TITLE
update CMakeList.txt

### PR DESCRIPTION
**Pull request by chujiangke**
update examples CMakeList.txt

### CODE REVIEW

**Comment by accelerated** [comment]
Hi @chujiangke what is the reason for this change? By adding executables directly they will appear as targets in your makefile which is what @mfontanini doesn't want. Also there is no linking provided for each target and the dependency should be on `RdKafka::rdkafka` imported library not `${RDKAFKA_LIBRARY}` directly.

**Comment by chujiangke** [comment]
because Ubuntu can't  build the example， so I change it。

**Comment by accelerated** [comment]
Could you post the error you're getting? This PR is definitely not the way to go.

**Comment by chujiangke** [comment]
cmakelist write like below
‘’‘create_example(producer)
create_example(buffered_producer)
create_example(consumer)
create_example(consumer_dispatcher)
create_example(metadata)
create_example(consumers_information)’

do cmake .
make 

and example  make nothing , so i change it , it works well.

**Comment by accelerated** [comment]
You need to explicitly call `make examples` and it will work. By default examples are not part of `make all`

**Comment by chujiangke** [comment]
oh thinks 。

**Pull request closed without merging**
