### PR TITLE
Added purge (aka async_flush) functionality

### PR DESCRIPTION
**Pull request by accelerated**
Added asynchronous flush capability.

### CODE REVIEW

**Comment by accelerated** [comment]
If you can merge this that would be great! Cheers!

**Comment by mfontanini** [comment]
I really thought I had merged this one, sorry :(. Anyway, I imagine you wanted the other one merged first so I went for that one.

**Comment by accelerated** [comment]
Before I resolve the conflicts, I actually had one question for you...i was debating if `purge` was the right name here or perhaps `async_flush`. Do you have any preferences? I think `async_flush` is easier to understand what it does, but there there's `produce` and `sync_produce` so people might wonder why intermixing sync and async as it's not consistent.

**Comment by mfontanini** [comment]
True, "purge" maybe sounds like you're getting rid of the messages rather than sending them. I'm not great at naming things but I think `async_flush` could work. I can't think of any other names... This is like some sort of "light flush" but that doesn't sound right.

**Comment by accelerated** [comment]
ok cool, I'll change the name and push the update in a few mins.

**Comment by mfontanini** [comment]
Thanks!

**Pull request merged**
