### PR TITLE
Try to fix travis

### PR DESCRIPTION
**Pull request by filimonov**
Old URL returns 404, picked new from official webpage: https://kafka.apache.org/downloads

### CODE REVIEW

**Comment by filimonov** [comment]
@accelerated  do you know smth about why the travis tests fail with the newest librdkafka?

**Comment by accelerated** [comment]
Looks to me like a race condition in the compacted processor and it gets stuck. Unfortunately I dont have access to Travis to restart the builds since i'm not the repo owner

**Comment by mfontanini** [comment]
Restarted the build but the same thing is probably going to happen.

**Comment by mfontanini** [comment]
Yeah, this is hanging on the new kafka version. Can you remove the new broker version in the travis matrix? We should figure out what's up with that test but that can wait.

**Comment by filimonov** [comment]
Let's try a bit older version first...

**Comment by filimonov** [comment]
v1.3.0 is failing too...

**Comment by filimonov** [comment]
So the problem started with https://github.com/edenhill/librdkafka/releases/tag/v1.0.0

**Comment by stevenylai** [comment]
The test is stuck when the consumer is trying to wait for eof for all partitions. I briefly tested with the new library, we need to first set: "enable.partition.eof": true, and second, rdkafka only returns eof to those are assigned to the consumer. I will try to open a PR and see if it fixes this

**Comment by mfontanini** [comment]
Thanks for the fix!

**Pull request merged**
