### PR TITLE
Remove MessageTimestamp constructor from time_point

### PR DESCRIPTION
**Pull request by mfontanini**
Relates to #128

### CODE REVIEW

**Comment by mfontanini** [comment]
@accelerated can you look into this one? I don't think we need that constructor, given the only one that constructs `MessageTimestamp`s is cppkafka itself.

**Comment by accelerated** [comment]
See my comment in the Issue thread. I can move it to the header file, that was my oversight or remove it, but I did make a note about that when I submitted the PR.

**Comment by mfontanini** [comment]
I don't think a user should be able to create `MessageTimestamp` (right now it can't). The user shouldn't be able to specify a `MessageTimestamp::TimestampType` because when calling `rd_kafka_producev` that goes away: at that point it's just a millisecond count.

Given that nothing constructs `MessageTimestamp` besides the `Message`, there's no point in allowing creating them from `time_point`

**Comment by mfontanini** [comment]
Yep, those are good ideas.

**Pull request merged**
